"""add_whatsapp_fields

Revision ID: 8377e55476d0
Revises: a9b8c7d6e5f4
Create Date: 2026-05-20 22:30:39.940810

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '8377e55476d0'
down_revision: Union[str, None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_alert_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('wa_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wa_number', sa.String(length=20), nullable=False),
    sa.Column('awaiting', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_sessions_wa_number'), 'whatsapp_sessions', ['wa_number'], unique=False)
    op.add_column('users', sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('whatsapp_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('whatsapp_alerts_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('whatsapp_alert_prefs', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'users', ['whatsapp_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'whatsapp_alert_prefs')
    op.drop_column('users', 'whatsapp_alerts_enabled')
    op.drop_column('users', 'whatsapp_verified')
    op.drop_column('users', 'whatsapp_number')
    op.drop_index(op.f('ix_whatsapp_sessions_wa_number'), table_name='whatsapp_sessions')
    op.drop_table('whatsapp_sessions')
    op.drop_table('whatsapp_otps')
    op.drop_table('whatsapp_alert_logs')
    # ### end Alembic commands ###
