"""fix inward_invoice_id FK to SET NULL on delete

Revision ID: a9b8c7d6e5f4
Revises: d1e2f3a4b5c6
Branch Labels: None
Depends On: None

"""
from typing import Sequence, Union
from alembic import op

revision: str = 'a9b8c7d6e5f4'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_NEW_CONSTRAINT = 'reconciliation_results_inward_invoice_id_fkey'


def upgrade() -> None:
    # Drop whatever the existing FK is named (auto-generated by Postgres when Alembic
    # called create_foreign_key(None, ...) without a naming convention)
    op.execute("""
        DO $$
        DECLARE
            cname TEXT;
        BEGIN
            SELECT tc.constraint_name INTO cname
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
                ON tc.constraint_name = kcu.constraint_name
                AND tc.table_schema = kcu.table_schema
            WHERE tc.table_name = 'reconciliation_results'
              AND tc.constraint_type = 'FOREIGN KEY'
              AND kcu.column_name = 'inward_invoice_id';

            IF cname IS NOT NULL THEN
                EXECUTE 'ALTER TABLE reconciliation_results DROP CONSTRAINT ' || quote_ident(cname);
            END IF;
        END $$;
    """)
    op.execute(f"""
        ALTER TABLE reconciliation_results
            ADD CONSTRAINT {_NEW_CONSTRAINT}
            FOREIGN KEY (inward_invoice_id)
            REFERENCES inward_invoices(id)
            ON DELETE SET NULL;
    """)


def downgrade() -> None:
    op.drop_constraint(_NEW_CONSTRAINT, 'reconciliation_results', type_='foreignkey')
    op.create_foreign_key(
        None,
        'reconciliation_results',
        'inward_invoices',
        ['inward_invoice_id'],
        ['id'],
    )
