"""initial

Revision ID: eff6c52fcc5c
Revises: 
Create Date: 2026-05-16 13:09:40.467273

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'eff6c52fcc5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('role', sa.Enum('layman', 'ca', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('debit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_high_value_cash', sa.Boolean(), nullable=False),
    sa.Column('source_bank', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_user_id'), 'bank_transactions', ['user_id'], unique=False)
    op.create_table('gstr2b_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('ims_action', sa.Enum('accept', 'reject', 'pending', name='imsaction'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gstr2b_records_supplier_gstin'), 'gstr2b_records', ['supplier_gstin'], unique=False)
    op.create_index(op.f('ix_gstr2b_records_user_id'), 'gstr2b_records', ['user_id'], unique=False)
    op.create_table('purchase_register_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_register_records_user_id'), 'purchase_register_records', ['user_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('financial_year', sa.String(length=7), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel'), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('declared_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scores_user_id'), 'risk_scores', ['user_id'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('gstr2b_id', sa.UUID(), nullable=True),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('matched', 'missing_in_2b', 'missing_in_books', 'amount_mismatch', 'tax_rate_mismatch', 'duplicate', 'pending_ims', name='reconciliationstatus'), nullable=False),
    sa.Column('match_confidence', sa.Integer(), nullable=False),
    sa.Column('taxable_diff', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_diff', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gstr2b_id'], ['gstr2b_records.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase_register_records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_user_id'), 'reconciliation_results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_results_user_id'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index(op.f('ix_risk_scores_user_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_purchase_register_records_user_id'), table_name='purchase_register_records')
    op.drop_table('purchase_register_records')
    op.drop_index(op.f('ix_gstr2b_records_user_id'), table_name='gstr2b_records')
    op.drop_index(op.f('ix_gstr2b_records_supplier_gstin'), table_name='gstr2b_records')
    op.drop_table('gstr2b_records')
    op.drop_index(op.f('ix_bank_transactions_user_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
